{{- if .Values.hpa.enabled -}}
{{- $root := . -}}
{{- range $componentName, $component := .Values.components }}
{{- if $component.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "steel-browser.componentFullname" (dict "root" $root "component" $componentName) }}
  labels:
    {{- include "steel-browser.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ kebabcase $componentName | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "steel-browser.componentFullname" (dict "root" $root "component" $componentName) }}
  minReplicas: {{ $root.Values.hpa.minReplicas }}
  maxReplicas: {{ $root.Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $root.Values.hpa.targetCPUUtilizationPercentage }}
    {{- if $root.Values.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $root.Values.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
